### ISSUE TITLE
A very easy and clear doc tool: docsify

### ISSUE THREAD

**Issue by zixia** [BUPT/awesome-chatbot#4]
```
docsify 4.7.0
A magical documentation site generator.

Simple and lightweight (~19kB gzipped)
No statically built html files
Multiple themes
```

It seems can be a good candidate for us to manage the paper list.

<https://docsify.js.org>

**Comment by 824zzy** [comment]
I think it is a better choice for documentation of paper's code implementation.
We need documents since code can not run successfully after we download directly.

**Comment by zixia** [comment]
We use docsify with our CAIC paper dictionary at <https://bupt.github.io/conversational-ai-club/>
