### ISSUE TITLE
2019-01-13 CAIC(Conversaional AI Club)第二十二次CAIC沙龙活动纪要

### ISSUE THREAD

**Issue by TuringLee** [BUPT/awesome-chatbot#61]
<< 本次沙龙通知: #60   << 

- 日期：2019-01-13 19:00-21:30
- 地点：北邮科研楼821会议室
- 轮值主席：李童俊 @TuringLee 
- 轮值副主席：陈光 @cgpeter96 
- 会员：李卓桓 @huan 张天津 @https://github.com/ozzie00   
- 新人：无

![wechatimg77](https://user-images.githubusercontent.com/17496872/51104082-085f6380-1820-11e9-8247-270622154018.jpeg)

授蛋仪式
-----
![wechatimg76](https://user-images.githubusercontent.com/17496872/51104100-144b2580-1820-11e9-88fc-f426de37e462.jpeg)

沙龙内容
----

![wechatimg74](https://user-images.githubusercontent.com/17496872/51104239-8facd700-1820-11e9-81aa-6dccd2a17064.jpeg)
- 李童俊 @TuringLee 用同样的模型训练两个任务。
> 利用阅读理解中QA和QG对称性，同时提升两个任务的结果。

![wechatimg78](https://user-images.githubusercontent.com/17496872/51104268-a6532e00-1820-11e9-8cc7-9a9d65bf9187.jpeg)
- 李卓桓 @huan 图网络在自然语言理解，语法树解析中的应用。

![wechatimg75](https://user-images.githubusercontent.com/17496872/51104839-39d92e80-1822-11e9-8e3a-91272282be75.jpeg)

- 张天津 @https://github.com/ozzie00 自然语言在高维空间中的表示。

## 沙龙结论
1. 增加了论文的wishlist.
2. 参会要求适当放宽，允许会员不分享论文参会，但是每次需挂靠一个分享论文的会员，每个会员一次会议只能被一个不分享论文的同学挂靠。
3. 第 二十三 次CAIC沙龙活动时间：1月6日（周日）19-22点
4. 第 二十三 次CAIC沙龙活动
    1. 轮值主席： 陈光 @cgpeter96 
    1. 轮值副主席：王石蕊 @wangshirui33 

## RSVP

注：“回复”操作，指的是回复本ISSUE留言

1. 如果对活动纪要有修订意见，请回复对本次沙龙纪补充
1. 如果参加下次沙龙活动，请回复下次自己的分享是 Oral（30-45分钟) 还是Poster（5-15分钟)
1. 如果计划邀请新朋友参加下次沙龙活动，请让新朋友回复一句话的自我介绍

**Comment by huan** [comment]
因为活动纪要已经发在Blog里面了，所以我就把这个Issue关闭啦，只留一个主要入口。

以后我们大家逐渐把会议纪要的习惯改成发表博客。

发PR引用的时候，可以引用博客在Issue里面的评论Issue，这样也可以同步到博客的评论区。:)
